image: Ubuntu
stack: jdk 13
build_script:
- mvn install
cache:
- /home/appveyor/.m2/repository/ -> pom.xml
artifacts:
  - path: testgenerator/target/testgenerator-1.0-SNAPSHOT.jar
    name: Used Vehicles 1.0 Snapshot
on_finish:
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
